version: "3.8"

services: 
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: