version: "3.8"

services: 
  # MongoDB Database
  mongodb:
    image: "mongo"
    volumes: 
      - data:/data/db
    env_file:
      - .env.dev
    ports:
      - "27017:27017"
    
  # ExpressJS Backend
  backend:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      ./.env.dev
    depends_on: 
      - mongodb

volumes:
  data:
