name: Deploy image to Amazon ECS

on:
  workflow_dispatch:

jobs:
  job1:
    permissions:
      id-token: write
      contents: read
    uses: anup-an/shopping-cart-react/.github/workflows/build-image.yml@master

  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: job1
    environment: production

    steps:
      - name: Download task definition
        id: download-task-def
        run: aws ecs shopping-cart-app --task-definition shopping-cart-app --query taskDefinition > task-definition.json
      
      - name: Fill in the image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
         task-definition: ${{ steps.download-task-def.outputs.task-definition }}
         image: ${{ needs.job1.outputs.newImage }}
         container-name: shopping-cart-react
