name: Deploy image to Amazon ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    permissions:
      id-token: write
      contents: read
    uses: anup-an/shopping-cart-react/.github/workflows/build-image.yml@master
    secrets: inherit

  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: job1
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ vars.ROLE_SESSION }}
          aws-region: eu-north-1

      - name: Download task definition
        id: download-task-def
        run: aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }} --query taskDefinition> task-definition.json
      
      - name: Fill in the image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
         task-definition: task-definition.json
         image: ${{ needs.job1.outputs.newImage }}
         container-name: shopping-cart-react
